### ISSUE TITLE
Javascript file size

### ISSUE THREAD

**Issue by gabrielrobert** [snipcart/snipcart-v3-feedback#1]
Is there any plan to make `snipcart.js` asset smaller? Maybe some kind of stripped builds excluding some features (EX: only one locale)?

https://cdn.snipcart.com/themes/v3.0.0-beta.1/default/snipcart.js **[338 KB]** 

![image](https://user-images.githubusercontent.com/5783827/58110266-36cdc080-7bbd-11e9-8ab6-b9261beebfce.png)

(P.S. V3 looks great, keep up the good work!)

**Comment by JeanSebTr** [comment]
Hey @gabrielrobert !

Thanks for reporting this. As you've already seen in #2 , there's plenty of places we've yet to improve to decrease our Javascript bundle.

We will review everything carefully as we approach the final V3 and we release the SDK.

**Comment by cekvenich** [comment]
This would be a deal killer for me. I maybe forced to write my own client side api with a different vendors:  as it is not clear to me how you would reduce bye > 90%.

**Comment by JeanSebTr** [comment]
Hey @cekvenich !

The Beta-3 is currently 382KB gzipped.

Looking at our dependencies graph, I see that some could be totally stripped out, some are duplicated between the SDK build and the theme and so on.

Like the V2, locales will be lazy-loaded.

Ultimately, lazy-loading can be used for loading ponyfill in older browsers.


There are limits to what we can remove though. The default theme must support all our features and be easy to extend for everybody. However, if you have a narrow set of requirements, the JS SDK will be available later in standalone to allow fully custom themes.


What would be your ideal payload size to use the cart?

**Comment by cekvenich** [comment]
If you are not able to make it small and preferment then you are making a case for doing carts server side, where the size is 0.
As to 'payload' size most people consider jquery large/heavy but people don't complain about mustache  'payload' size.  Clearly you'd have to give up on using web-pack approaches to be able to represent a client-side cart in a good light, in order to get to an acceptable size and performance. Based on your response above: I suggest you not release v3, instead start v4 with a different approach or a different team - that can explore optimal size and still have the functionality. Of course, same team and same approach will give you same result: That snipcart team have demonstrated that carts should be server side.

**Comment by JeanSebTr** [comment]
@cekvenich maybe that wasn't clear, what I said is there's plenty of room to decrease the script size significantly. It's just not our main priority at the moment.

For fun, a colleague gave it a try yesterday and slashed ~100KB in a few minutes of work. This just proves to us that:
1. we should keep the payload size in checks to not increase it with useless stuff
2. again, plenty of room to improve

Snipcart promotes a front-end centric approach. If you want to do all this server-side, good for you, but Snipcart might not be the right fit for you.

Lastly, the goal of this repo is to be more open about our development process and collect constructive feedback. We won't tolerate trolling or insults.

**Comment by kieranphilipbrown** [comment]
Really looking forward to any size decreases you can make in future versions where you can.

Love the look of the new cart by the way 👌 Really happy with it!

**Comment by mdings** [comment]
I was playing around with Snipcart today and I think it's even the best cart out in the market with "headless" possibilities. That was until I saw the filesize of the included javascript file coming in at 416kb.. Frankly that's just way too big of a resource for me to include in order to build a performant, lean and fast-loading PWA. And even a reason to abandon Snipcart altogether, which is a shame because it's great otherwise. Any plans to address this issue in the short-term?

**Comment by JeanSebTr** [comment]
Hi @mdings!

Thanks for the feedback! We've made some improvements a few releases ago to the payload size. We've almost reached the limit of what we can downsize to while keeping all features.

We are exploring other solutions like code splitting by feature, lazy loading, or alternative stripped-down versions. However, our focus is on simplicity for developers, so any change to our packaging must not impact this.

I can't promise a specific ETA but more payload improvements are coming.


That being said, Snipcart can fully be loaded asynchronously and shouldn't affect page load unless you're expecting customers on a very slow network. If you notice anything about Snipcart's initialization that does affect page load, please open an issue and we'll address those 😄

Also, if you want to minimize delay until Snipcart is operational on a page, you can use `dns-prefetch` and `preconnect` to `https://app.snipcart.com/`. On normal networks, roundtrips are generally more costly than payload size.

**Comment by mdings** [comment]
Thanks for your fast reply @JeanSebTr and your elaborate answer!

**Comment by thatfrankdev** [comment]
Hi there,

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

Sometime in 2021, we will be rolling out a Discourse forum instance so we can have a decent community support channel.

Rest assured our bundle size is an ongoing concern, and we'll keep looking at ways to bring it within a reasonable size range as our platform grows.

That being said, if you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks.
