### ISSUE TITLE
Can't get past address field

### ISSUE THREAD

**Issue by budparr** [snipcart/snipcart-v3-feedback#36]
**Integration URL**

production site (not my site) https://awkosock.com/products/socks/starks-rec-tall/#/checkout

Snipcart v3.0.1

**Describe the bug**
The address lookup functionality seems to freeze the rest of the process.

**To Reproduce**
1. Go to checkout
2. Click on Address and input an address
3. click on "Continue to Shipping"
4. No error. Nothing happens. 

**Screenshots**
![Screenshot 2019-10-29 13 44 30](https://user-images.githubusercontent.com/115347/67794715-814c4680-fa53-11e9-9a7d-14e78fefee89.jpg)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Safari 13, Chrome 78

**Comment by thatfrankdev** [comment]
Thanks for reporting @budparr!

There are two issues here:

1. This actions lacks feedback when an error occurs. We have a handful of ongoing work items aimed at fixing these. They'll get addressed quite soon.

2. Our type-ahead address suggestion box is backed by Algolia Places, who abruptly stopped returning postal codes yesterday. That's why selecting an option in the suggestions list does not fill the address form entirely. We are currently working at making our address suggestion engine more robust.

Again, thanks for dropping by 👍

**Comment by budparr** [comment]
Sounds good. I tested with bypassing the address autofill and it did indeed work.

**Comment by medarke** [comment]
is this working now then?

**Comment by JeanSebTr** [comment]
> is this working now then?

@medarke The issue that was reported here is fixed since 3.0.2. However, we did not yet implement an alternative address provider.
