### ISSUE TITLE
Missing an option to manage the cart opening on add items

### ISSUE THREAD

**Issue by wab** [snipcart/snipcart-v3-feedback#46]
Hi There,

It seems there is no option on api / sdk for prevent cart from auto-opening when the user add an item on it. 
Or perhaps there is another way to use the cart ?
It could be very usefull to add this kind of option, like the 'autopop' boolean on v2.
Thanx

**Comment by rcobiella** [comment]
I have the same problem. Is this not possible at all?

**Comment by StanislavSt** [comment]
Same problem here. Anyone found a solution ?

**Comment by rcobiella** [comment]
is this project even active?

**Comment by couellet** [comment]
Yes it is @rcobiella but our team is off for the holidays ;) Back at the office on Monday.

We don't have a way to control this behavior just yet, this is something we'll add in the future though.

**Comment by rcobiella** [comment]
Thank you @couellet! 

It's a much needed feature, handling the animations would improve the integration into the website's design a lot IMO. In my experience (only used v3 in one site for now, but planning to use it on two more soon), having a full sized container animating in from the side is a bit off putting. Definitely not a drama, but it would be nice to be able to change this!

**Comment by doug-matthews** [comment]
Hey @couellet, any updates on this feature? this issue is preventing us from launching our product.

**Comment by estruyf** [comment]
Just launched, but was hoping this was already supported, as it was possible in v2. What is the status about this?

**Comment by JeanSebTr** [comment]
Hey everyone,

This has been prioritized to be rolled out in a few releases. We'll let you know once it's released.

**Comment by pgmichael** [comment]
It's now possible to prevent the cart from opening automatically since we've released the 3.0.12!

Detailed instruction on how to do so can be found in the "Changing the cart summary behavior" section of this entry: https://docs.snipcart.com/v3/setup/cart-summary

If you choose to do so, make sure you've upgraded the `snipcart.js` script to the latest version: https://docs.snipcart.com/v3/setup/installation

Cheers!

**Comment by Unbel** [comment]
greetings!
i think  #**changing-the-cart-summary-behavior** paragraph was removed from https://docs.snipcart.com/v3/setup/cart-summary   post,
because no information there about: we can use 
`<div hidden id="snipcart" data-api-key="<API_KEY>" data-config-add-product-behavior="none"></div> `
to prevent the cart from opening automatically.
cheers!

**Comment by thatfrankdev** [comment]
Hi @Unbel, the section has been moved to the installation page, right here: https://docs.snipcart.com/v3/setup/installation#data-config-add-product-behavior
