### ISSUE TITLE
Javascript SDK function "Snipcart.api.cart.setShippingInformation" allows anyone to change the shipping price when using Shipping webhook

### ISSUE THREAD

**Issue by Geoffrey60fps** [snipcart/snipcart-v3-feedback#65]
Hello,

While testing the V3, I found out that when you're using a Shipping webhook, there is not verification made on the shipping price given by the webhook and the shipping price set in the frontend.

Using the method below in the developer console allows me to process an order with a shipping price of 0.
```
Snipcart.api.cart.setShippingInformation({
        method: 'My description',
        cost: 0,
 })
```

This seems very dangerous to me and should not be possible.

**Comment by thatfrankdev** [comment]
Hi @Geoffrey60fps,

Although this is possible via the JS SDK, our final [order validation process](https://docs.snipcart.com/v3/setup/order-validation), that also validates the price of items, will fail if no shipping rate from your webhook matches what's set on the cart.

**Comment by Geoffrey60fps** [comment]
I see, but it raises a problem.

My shipping rates are the following:
![Screenshot-2020-05-14-at-14 22 49](https://user-images.githubusercontent.com/62067113/81934076-9f902300-95ee-11ea-8e6b-717982ce4083.png)

I ran this in the console:
`Snipcart.api.cart.setShippingInformation({
     method: 'Livraison par Seabourne',
     cost: 0,
})`

The order processes correctly, as the shipping rate exists in our webhook response, but the corresponding shipping method is wrong. 
With that, anyone can select a shipping method and changing it's fee with another one.

**Comment by thatfrankdev** [comment]
Thanks for these details.

In that particular case the order validation succeeds because other rates have 0 as their prices, so technically the total order price is correct. However I can definitely see how this can go undercover when order fulfillment occurs.

A fix for that this issue is definitely jumping in our roadmap.

Thanks for reporting it 🙇

**Comment by Geoffrey60fps** [comment]
Thanks alot @thatfrankdev !

**Comment by thatfrankdev** [comment]
Hi there,

We are about to archive this repository, as its purpose was initially to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

A fix for this issue is still on the roadmap, we'll come to it.

If you need any support or if you want to submit feedback, please reach out to support@snipcart.com. Our team will be happy to help.

Thanks
