### ISSUE TITLE
Manage multiple forms submission 

### ISSUE THREAD

**Issue by filippolcr** [snipcart/snipcart-v3-feedback#81]
I noticed that by repeatedly clicking the submit button of your forms I make multiple calls.

I think it is better to apply some strategy that prevents multiple forms submission.

**Comment by thatfrankdev** [comment]
Thanks for reporting this @filippolcr 

So sorry we couldn't respond to this one sooner. I believe this has been improved since you submitted this. If you still have issues regarding this, please reach out to support@snipcart

We are about to archive this repository, as its goal was to collect feedback when Snipcart v3 was in its beta phase. That's behind us now.

Thanks
